use [ORD_Matheny_201312053D];

delete from [RapTAT].[span];
Print 'Delete span rows Complete';
delete from [RapTAT].[sentence];
Print 'Delete sentence rows Complete';
delete from [RapTAT].[document];
Print 'Delete document rows Complete';
delete from [RapTAT].[link_type_concept1];
Print 'Delete link_type_concept1 rows Complete';
delete from [RapTAT].[link_type_concept2];
Print 'Delete link_type_concept2 rows Complete';
delete from [RapTAT].[link];
Print 'Delete link rows Complete';
delete from [RapTAT].[link_type];
Print 'Delete link_type rows Complete';
delete from [RapTAT].[rel_ann_attr];
Print 'Delete rel_ann_attr rows Complete';
delete from [RapTAT].[annotation];
Print 'Delete annotation rows Complete';
delete from [RapTAT].[annotator];
Print 'Delete annotator rows Complete';
delete from [RapTAT].[rel_con_attr];
Print 'Delete real_con_attr rows Complete';
delete from [RapTAT].[rel_attr_attrval];
Print 'Delete rel_attr_attrval rows Complete';
delete from [RapTAT].[attr_value];
Print 'Delete attr_value rows Complete';
delete from [RapTAT].[attribute];
Print 'Delete attribute rows Complete';
delete from [RapTAT].[concept];
Print 'Delete concept rows Complete';
delete from [RapTAT].[schemas];
Print 'Delete schemas rows Complete';
--delete from [RapTAT].[full_annnotation_with_relationships];
--Print 'Delete schemas rows Complete';